spring:
  application:
    name: cicd-study

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # Graceful Shutdown: 종료 시 처리 중인 요청 완료 대기
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Graceful Shutdown 활성화
server:
  shutdown: graceful
