name: on-premise-cicd
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Set Tags Name'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.set-version.outputs.VERSION_NAME }}
    steps:
      - id: set-version
        run: |
          # 태그에서 .을 -로 치환하여 저장
          VERSION=$(echo "${{ github.event.inputs.tags }}" | sed 's/\./-/g')
          echo "VERSION_NAME=$VERSION" >> $GITHUB_OUTPUT

      - name: Check Version Name
        run: echo "Check Version --> ${{ steps.set-version.outputs.VERSION_NAME }}"

      - name: Checkout Source Code
        uses: actions/checkout@v4  # 최신 안정 버전 4 권장
        with:
          ref: ${{ github.event.inputs.tags }}

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew  # +w가 아니라 실행 권한인 +x여야 합니다

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradlew
        run: ./gradlew clean test bootJar

      - name: Add version to release
        run: |
          mv build/libs/cicd-study-0.0.1-SNAPSHOT.jar build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # v4가 현재 안정 버전입니다
        with:
          name: cicd-study-application
          path: build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar
